### ISSUE TITLE
Fix for MediaRecorder on Mac

### ISSUE THREAD

**Issue by demian85** [electron/libchromiumcontent#253]
Hi,

I reported [this issue](https://bugs.chromium.org/p/chromium/issues/detail?id=678269) 5 days ago and someone [published a patch](https://codereview.chromium.org/2617143003) targeted for Chrome 57.
I've been struggling with this issue for at least 2 weeks. My project development is currently stuck because it depends on this feature to work.

As you can see in the issue report, I attached [a chrome extension demo](https://bugs.chromium.org/p/chromium/issues/attachment?aid=266198) that confirms bug is fixed in latest Chromium build with patch applied.

Please, I would like to know what it takes for this patch to be applied to the next libchromiumcontent release without the need of having to compile from source myself (tried and it's not working... #252)

Thanks.

**Comment by kevinsawicki** [comment]
@demian85 can you open a pull request in this repository that adds the patch to the `patches` folder and we can take a look at the scope of it?

**Comment by kevinsawicki** [comment]
You can see an example of another patch pull request at https://github.com/electron/libchromiumcontent/pull/251

**Comment by demian85** [comment]
Great, thanks!

**Comment by kevinsawicki** [comment]
Fixed by #255

**Comment by demian85** [comment]
Well, this is disturbing. I've just downloaded electron 1.4.15 and bug is still there -_-

**Comment by kevinsawicki** [comment]
> Well, this is disturbing. I've just downloaded electron 1.4.15 and bug is still there -_-

Could there be another patch or change that needed to go with it?

**Comment by demian85** [comment]
Well, I just tested on my compiled development version and it works... But release version does not. Wtf? Can you please explain what's the difference and how can I create a distributable release of electron? I have a bunch of files and I don't know where to put them. Also, my compiled version is based on Chrome 54. Perhaps that has something to do? When is the electron based on Chrome 54 release planed?

**Comment by demian85** [comment]
ping @kevinsawicki 

I keep playing with electron to see if issue still exists or no and where.
I just found out that my compiled version based on chrome 54 works, chrome canary too, but current chrome stable does not work.
So perhaps the issue depends on another fix already in chrome 54, that's why using the latest electron stable build does not work, it's based on chrome 53, right?

What I also see in my console is that every webm blob chunk has mime type assigned, whereas on Chrome 53 it doesn't. Suspicious.

So, could you please tell me when the new version of electron will be released?

Thanks.

**Comment by kevinsawicki** [comment]
> So perhaps the issue depends on another fix already in chrome 54, that's why using the latest electron stable build does not work, it's based on chrome 53, right?

Yeah, 1.4.15 ships with Chrome 53.

> So, could you please tell me when the new version of electron will be released?

1.5.0 based on Chrome 54 will be released to beta most likely this week.

**Comment by kevinsawicki** [comment]
@demian85 1.5.0 is now out.

**Comment by demian85** [comment]
Right, it's working (almost)

Mouse cursor is not visible yet. I was told it has been fixed in Chrome 54 so I'll need to investigate further on this issue again. Will update my previous issue on electron repo.

**Comment by demian85** [comment]
Guys, thanks for your support, but unfortunately, this bug is still there and a guy from Chromium [confirms it](https://bugs.chromium.org/p/chromium/issues/detail?id=688490#c12).
This is a nightmare, recording works "sometimes"...
I'd appreciate help on how to build Electron based on Chrome 58, just for me and for the sake of my project!
Do I need to make changes in the source code or just modifying configuration values is enough? Is there any guide?

Thanks a lot.
